name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Change dir to bin
        run: cd bin

      - name: Run scrapey
        run: ./scrapey version
